[package]
name = "analysis"
version = "0.2.0"
edition = "2021"
[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
model = { path = "../model" }
uuid = { version = "1", features = ["v4"] }
