[package]
name = "delta-io"
version = "0.2.0"
edition = "2021"
[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
csv = "1.3"
anyhow = "1.0"
uuid = { version = "1", features = ["v4", "serde"] }
model = { path = "../crates/model" }
