name: Delta – Build installers (Windows + macOS)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

env:
  APP_DIR: apps/desktop

jobs:
  windows:
  name: Windows – EXE + NSIS
  runs-on: windows-2022
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Enable Corepack + pnpm
      run: |
        corepack enable
        corepack prepare pnpm@latest --activate

    - name: Install frontend deps
      working-directory: apps/desktop
      run: pnpm install

    - name: Install Tauri CLI (dev dep)
      working-directory: apps/desktop
      run: pnpm add -D @tauri-apps/cli

    - name: Print tauri info (sanity)
      working-directory: apps/desktop
      run: pnpm tauri info

    - name: Setup Rust (stable MSVC)
      uses: dtolnay/rust-toolchain@stable

    - name: Install NSIS (for installer)
      run: choco install nsis -y

    # Build once; NSIS will produce the installer AND Cargo will emit a raw .exe in target\release
    - name: Build NSIS installer (also compiles exe)
      working-directory: apps/desktop
      run: pnpm tauri build --bundles nsis

    - name: Upload artifacts (Windows)
      uses: actions/upload-artifact@v4
      with:
        name: delta-windows
        path: |
          apps/desktop/target/release/*.exe
          apps/desktop/target/release/bundle/nsis/**
        if-no-files-found: error
