name: Delta – Build installers (Windows + macOS)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  windows:
    name: Windows – EXE + NSIS
    runs-on: windows-2022   # pin; change to windows-latest later if you like
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack / pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install frontend deps
        working-directory: apps/desktop
        run: pnpm install

      # Official Tauri Action: sets up Rust, caches Cargo, installs NSIS on Windows
      - name: Build (app + NSIS)
        uses: tauri-apps/tauri-action@v0
        with:
          projectPath: apps/desktop
          includeDebug: false
          args: --bundles app,nsis

      - name: Upload artifacts (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: delta-windows
          path: |
            apps/desktop/target/release/bundle/app/**
            apps/desktop/target/release/bundle/nsis/**
          if-no-files-found: error

  macos:
    name: macOS – .app + .dmg
    runs-on: macos-14        # pin; change to macos-latest later if you like
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack / pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install frontend deps
        working-directory: apps/desktop
        run: pnpm install

      - name: Build (app + dmg)
        uses: tauri-apps/tauri-action@v0
        with:
          projectPath: apps/desktop
          includeDebug: false
          args: --bundles app,dmg

      - name: Upload artifacts (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: delta-macos
          path: |
            apps/desktop/target/release/bundle/app/**
            apps/desktop/target/release/bundle/dmg/**
          if-no-files-found: error
