name: Delta – Build installers (Windows + macOS)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    # Pin runners to avoid the Sept 2025 image switch surprise.
    # You can switch back to -latest later.
    strategy:
      matrix:
        os: [windows-2022, macos-14]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Let the action pick the right cache automatically
          cache: 'pnpm'

      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: Prepare pnpm
        run: corepack prepare pnpm@latest --activate

      - name: Install frontend deps
        working-directory: apps/desktop
        run: pnpm install

      # 🔑 The official Tauri action – it installs Rust, caches Cargo,
      #    and on Windows it installs NSIS automatically.
      - name: Build with Tauri Action
        uses: tauri-apps/tauri-action@v0
        with:
          projectPath: apps/desktop
          # Choose what to build on each OS
          # Windows: portable exe + NSIS installer
          # macOS:  .app + .dmg
          includeDebug: false
          args: >-
            --bundles
            ${{ startsWith(matrix.os, 'windows') && 'app,nsis' || 'app,dmg' }}
        env:
          # (Optional) If your frontend needs env vars, add them here
          # VITE_API_BASE: ${{ secrets.VITE_API_BASE }}
          # TAURI private key vars only if you code-sign. Otherwise omit.
          # TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          # TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ startsWith(matrix.os, 'windows') && 'delta-windows' || 'delta-macos' }}
          path: |
            apps/desktop/target/release/bundle/**/*
          if-no-files-found: error
